options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'launcher'
      - '--gen2'
      - '--runtime=python312'
      - '--region=europe-west1'
      - '--source=.'
      - '--entry-point=main'
      - '--trigger-http'
      - '--allow-unauthenticated'